language: node_js
node_js: stable
addons:
  ssh_known_hosts:
    - 1991421.cn:29554
install:
- npm install
script:
- hexo g
after_script:
- cd ./public
- git init
- git config user.name "alanhg"
- git config user.email "qianghe421@163.com"
- git add .
- git commit -m "update"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
- ssh -p 29554 root@1991421.cn "cd /var/www/alanhg.github.io;npm install --production;hexo g"

branches:
  only:
  - source
env:
  global:
  - GH_REF: github.com/alanhg/alanhg.github.io.git
notifications:
  email:
  - i@alanhe.me
