language: node_js
node_js: stable
addons:
  ssh_known_hosts:
    - 108.160.132.49:22
before_install:
  - openssl aes-256-cbc -K $encrypted_95ec2afed622_key -iv $encrypted_95ec2afed622_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm install
script:
  - hexo g
after_script:
  - cd ./public
  - git init
  - git config user.name "alanhg"
  - git config user.email "qianghe421@163.com"
  - git add .
  - git commit -m "update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
  - rsync -az -vv --delete -e 'ssh -p 22' public/** root@108.160.132.49:/var/www/static-html
branches:
  only:
    - source
env:
  global:
    - GH_REF: github.com/alanhg/alanhg.github.io.git
notifications:
  email:
    - i@alanhe.me
