# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ source ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install  Dependencies
        run: yarn install
      - name: Build
        run: ｜
          hexo clean
          hexo g
          export HEXO_ALGOLIA_INDEXING_KEY=fb41a459b46e7dda7af65d45ad5f8432
          hexo algolia
          cd ./public
      - name: Deploy GitHub Master
        run: ｜
          git init
          git config user.name "Alan He"
          git config user.email "alan@1991421.cn"
          git add .
          git commit -m "update"
          git push --force --quiet master:master
      - name: SSH agent
           uses: webfactory/ssh-agent@v0.2.0
           with:
              ssh-private-key: ${{ secrets.BLOG_DEPLOY_KEY }}
      - name: Deploy VPS
        run: ｜
          ssh-keyscan 1991421.cn >> ~/.ssh/known_hosts
          rsync -az -vv --delete -e 'ssh -p 22' ./** root@1991421.cn:/var/www/blog/static-html

